### ISSUE TITLE
Missing fields error

### ISSUE THREAD

**Issue by mnewsted** [SuffolkLITLab/docassemble-AppearanceEfile#1] opened 2022-10-13 18:45 UTC
Not sure if there's something wrong with the Tyler staging server, but I encountered the following error on at least 4 separate cases. It appears after the Fee waiver year of birth question. I'm not able to complete a filing (I tried with and without a jury demand).

---case info---
Tazewell County, 2022-DC-000001 and 2020D10
Champaign County, 2020D 000192  and 2015D 000382

---error message---
id: missing-fields
Package: docassemble.AppearanceEfile 0.1.3b1; AL-2.15.0

Missing fields
Notice: you are in interview author mode!

To efile using the proxy server, you need to fix some problems in your interview.

Something went wrong when processing your interview:

response_code: 500, data: {‘cause0’: ‘java.util.EmptyStackException’, ‘message’: ‘java.util.EmptyStackException’, ‘url’: ‘//jurisdictions/illinois/filingreview/courts/tazewell/filing/check’, ‘status’: ‘500’}

**Comment by BryceStevenWilley** [comment] 2022-10-24 19:23
This was fixed on the proxy server side in https://github.com/SuffolkLITLab/EfileProxyServer/commit/8c917f0d968f2856775fc6ad5c41baeece195b28, and I think we've both confirmed it's fixed since that fix!

**Closed by BryceStevenWilley** 2022-10-24 19:23 UTC
